module.exports={
    "Actions":{
        "GenerateModels":"action:generate.models",
        "TestConnection":"action:test-connection"
    },
    "Results":{
        "ModelsGenerated":"result:models-generated",
        "ConnectionTestPast":"result:connection-authentication-past",
        "ConnectionTestFailed":"result:connection-authentication-failed"
    }
};